apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nsjdgu28q-go
  janus-idp.io/tekton: nsjdgu28q-go
  backstage.io/kubernetes-id: nsjdgu28q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nsjdgu28q-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
